"""empty message

Revision ID: 1afcf28bc401
Revises: ba250a5fc1b2
Create Date: 2023-12-12 13:25:01.589901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afcf28bc401'
down_revision = 'ba250a5fc1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_order_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'state_order', ['state_order_id'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_role_id_fkey', 'state_order', ['role_id'], ['id'])
        batch_op.drop_column('state_order_id')

    # ### end Alembic commands ###
