"""empty message

Revision ID: 630b29c95682
Revises: 7b26e670327d
Create Date: 2023-12-11 16:11:08.481475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630b29c95682'
down_revision = '7b26e670327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('price_sweet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_sweet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
